### ISSUE TITLE
Modal.open() Error

### ISSUE THREAD

**Issue by oras** [dougludlow/ng2-bs3-modal#131]
```
HTML1300: Navigation occurred.
File: index.html
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
EXCEPTION: Error in Dashboard/Nav/nav.html:24:15 caused by: Unable to get property 'open' of undefined or null reference
ORIGINAL EXCEPTION: Unable to get property 'open' of undefined or null reference
ORIGINAL STACKTRACE:
TypeError: Unable to get property 'open' of undefined or null reference
   at ParentComponent.prototype.open (eval code:46:9)
   at AppComponent.prototype.showNewTestForm (eval code:36:9)
   at _View_AppComponent0.prototype._handle_click_33_0 (Function code:184:3)
   at Anonymous function (eval code:9437:21)
   at Anonymous function (eval code:1525:13)
   at Anonymous function (eval code:1638:108)
   at ZoneDelegate.prototype.invoke (http://localhost:64571/node_modules/zone.js/dist/zone.js:230:13)
   at onInvoke (eval code:6206:25)
   at ZoneDelegate.prototype.invoke (http://localhost:64571/node_modules/zone.js/dist/zone.js:230:13)
   at Zone.prototype.runGuarded (http://localhost:64571/node_modules/zone.js/dist/zone.js:128:21)
ERROR CONTEXT:
[object Object]
=========================================================
import { Component, ViewChild, AfterViewInit  } from '@angular/core';
import { TestService } from './toh/test.service';
import { DesktopComponent } from './desktop.component';
import { Test } from './toh/test';
import {  ModalComponent } from 'ng2-bs3-modal/ng2-bs3-modal';
declare var $: JQueryStatic;

@Component({
    selector: 'test-form',
    providers: [TestService, DesktopComponent],
    templateUrl: '/../Dashboard/Forms/testForm.html',
   
})

export class ParentComponent  {
    active: boolean;
    submitted: boolean;
    newTest: Test;
    tests: Test[];
    @ViewChild('modal')
    modal: ModalComponent;
  

    constructor(private testService: TestService, private desktop: DesktopComponent) { }

    ngOnInit() {
        this.active = true;
        this.submitted = false;
        this.newTest =  {
            tid: '',
            description: '',
            owner: '',
            status: false,
            bug: 0,
            run: false
        };
    }
    
   

    onSubmit(newTest:Test){
        this.testService.addTest(newTest)
            .subscribe(value=>this.submitSuccess(),
            err => {
                // Log errors if any
                console.log(err);
            });
        
    }

    submitSuccess() {
        this.submitted = true;
        this.desktop.getTests()
        this.newTest.tid = this.newTest.description = this.newTest.owner = '';
        
    }

    public open() {
        this.modal.open();
    }

    public close() {
        this.modal.close();
    }
}
====================================================================
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from "@angular/forms";
import { HttpModule, JsonpModule } from '@angular/http';
import { AppComponent } from './app.component';
import { DesktopComponent } from './desktop.component';
import { DatePickerModule } from 'ng2-datepicker';
import { ParentComponent } from './test-form.component';
import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';


@NgModule({
    imports: [
        BrowserModule,
        HttpModule,
        JsonpModule,
        FormsModule,
        Ng2Bs3ModalModule
        
    ],
    declarations: [
       AppComponent,
        DesktopComponent,
        ParentComponent
        
    ],

    bootstrap: [AppComponent, DesktopComponent]
})

export class AppModule {}

======================================================
<!DOCTYPE html>
<html>
  <head>
   
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="styles.css">
      
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.js"></script>
     
     <!-- Polyfill(s) for older browsers -->
      <script src="node_modules/primeui/primeui-ng-all.min.js"></script>
      <script src="node_modules/core-js/client/shim.min.js"></script>
      <script src="node_modules/zone.js/dist/zone.js"></script>
      <script src="node_modules/reflect-metadata/Reflect.js"></script>
      <script src="node_modules/systemjs/dist/system.src.js"></script>
      <script src="systemjs.config.js"></script>
    <script>
      System.import('app').catch(function(err){ console.error(err); });
    </script>
  </head>

  <body>
    <my-app>Loading...</my-app>
   <my-desktop></my-desktop>
  </body>
</html>

==========================================================
{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "docker-build": "docker build -t ng2-quickstart .",
    "docker": "npm run docker-build && docker run -it --rm -p 3000:3000 -p 3001:3001 ng2-quickstart",
    "pree2e": "npm run webdriver:update",
    "e2e": "tsc && concurrently \"http-server -s\" \"protractor protractor.config.js\" --kill-others --success first",
    "lint": "tslint ./app/**/*.ts -t verbose",
    "lite": "lite-server",
    "test": "tsc && concurrently \"tsc -w\" \"karma start karma.conf.js\"",
    "test-once": "tsc && karma start karma.conf.js --single-run",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "webdriver:update": "webdriver-manager update"
  },
  "keywords": [],
  "author": "",
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/angular/angular.io/blob/master/LICENSE"
    }
  ],
  "dependencies": {
    "@angular/common": "~2.1.2",
    "@angular/compiler": "~2.1.2",
    "@angular/core": "~2.1.2",
    "@angular/forms": "~2.1.2",
    "@angular/http": "~2.1.2",
    "@angular/platform-browser": "~2.1.2",
    "@angular/platform-browser-dynamic": "~2.1.2",
    "@angular/router": "~3.1.2",
    "@angular/upgrade": "~2.1.2",
    "angular-in-memory-web-api": "~0.1.13",
    "core-js": "^2.4.1",
    "es6-shim": "^0.35.1",
    "express": "^4.14.0",
    "jasmine": "^2.5.2",
    "jasmine-jquery-matchers": "^1.2.2",
    "jquery": "^3.1.1",
    "karma": "^1.3.0",
    "karma-chrome-extra-launcher": "^0.1.0",
    "karma-jasmine": "^1.0.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-spec-reporter": "^0.0.26",
    "lodash": "^4.16.6",
    "moment": "^2.15.2",
    "mydatepicker": "^1.0.0",
    "angular2-modal": "^2.0.2",
    "ng2-bs3-modal": "^0.10.4",
    "node-static": "^0.7.9",
    "phantomjs-prebuilt": "^2.1.13",
    "reflect-metadata": "^0.1.8",
    "rimraf": "^2.5.4",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "^0.19.41",
    "tslint": "^3.15.1",
    "typescript": "^2.0.9",
    "typings": "^2.0.0",
    "uglify": "^0.1.5",
    "zone.js": "^0.6.26"
  },
  "devDependencies": {
    "@types/core-js": "^0.9.34",
    "@types/jasmine": "^2.5.36",
    "@types/node": "^6.0.46",
    "@types/selenium-webdriver": "^2.53.33",
    "bootstrap": "^3.3.7",
    "canonical-path": "0.0.2",
    "concurrently": "^3.1.0",
    "http-server": "^0.9.0",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-htmlfile-reporter": "^0.3.4",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "lite-server": "^2.2.2",
    "lodash": "^4.16.4",
    "protractor": "4.0.9",
    "rimraf": "^2.5.4",
    "tslint": "^3.15.1",
    "typescript": "^2.0.3",
    "webdriver-manager": "10.2.5"
  },
  "repository": {},
  "optionalDependencies": {
    "bootstrap": "^3.3.7"
  }
}

```

**Comment by oras** [comment]
the html form modal

<link rel="stylesheet" href="forms.css">

<modal #modal>
    <modal-header>
        <h4 class="modal-title">I'm a modal!</h4>
    </modal-header>
    <modal-body>
        Hello World!
    </modal-body>
    <modal-footer>
        <button type="button" class="btn btn-default" data-dismiss="modal" (click)="modal.dismiss()">Cancel</button>
        <button type="button" class="btn btn-primary" (click)="modal.close()">Ok</button>
    </modal-footer>
</modal>

**Comment by oras** [comment]
Now I get the following error

caused by: Object doesn't support property or method 'modal'

**Comment by oras** [comment]
I needed to include the Jquery and bootstrap different because using system js.
now no errors are display but the popup refuse to show up,
any clues?

**Comment by oras** [comment]
Ok Installed  bootstrap 4, and used the following dependencies on the following link:
http://v4-alpha.getbootstrap.com/getting-started/introduction/

work like a charm !

**Comment by dougludlow** [comment]
@oras thanks for documenting your experience. Glad you got it all working!
