### ISSUE TITLE
jquery is not defined error

### ISSUE THREAD

**Issue by ivytruong** [dougludlow/ng2-bs3-modal#132]
Hello,

I am new to angular2 and is developing a small app for my job. I google and found your modal module that is for angular2 and bootstrap3.7 . I install the package and the compiler did not give any error but when i run the page, it will log the error of the "jquery is not defined". I wonder is there a way you do to fix it?

**Comment by hyacinthxinxin** [comment]
- inline template:34:0 caused by: jQuery is not defined
ReferenceError: jQuery is not defined

the same issue.

**Comment by fxcosta** [comment]
Same issue: 
inline template:94:8 caused by: jQuery is not defined

after a npm update this stop work

**Comment by JoSeTe4ever** [comment]
It is happening to me as well, Just added the dependency on the package.json file , npm install and Jquery is not defined ...

**Comment by dougludlow** [comment]
There are so many permutations as far as project setups are concerned. Are you using webpack? angular-cli? SystemJs? Plain ol' npm?

**Comment by verasztol** [comment]
Hi!

Same for me. I use the default project config of webstorm angular-cli.

EXCEPTION: Uncaught (in promise): Error: Error in ./ModalDialogComponent class ModalDialogComponent - inline template:1:2 caused by: jQuery is not defined
ReferenceError: jQuery is not defined
    at ModalInstance.init (http://localhost:4200/vendor.bundle.js:69449:23)
    at new ModalInstance (http://localhost:4200/vendor.bundle.js:69411:14)
    at new ModalComponent (http://localhost:4200/vendor.bundle.js:25788:25)
    at new Wrapper_ModalComponent (/Ng2Bs3ModalModule/ModalComponent/wrapper.ngfactory.js:7:18)
    at View_ModalDialogComponent1.createInternal (/AppModule/ModalDialogComponent/component.ngfactory.js:87:30)
    at View_ModalDialogComponent1.AppView.create (http://localhost:4200/vendor.bundle.js:83898:21)
    at View_ModalDialogComponent1.DebugAppView.create (http://localhost:4200/vendor.bundle.js:84350:44)
    at TemplateRef_.createEmbeddedView (http://localhost:4200/vendor.bundle.js:61100:14)
    at ViewContainerRef_.createEmbeddedView (http://localhost:4200/vendor.bundle.js:61361:52)
    at NgIf.set [as ngIf] (http://localhost:4200/vendor.bundle.js:73207:37)
    at Wrapper_NgIf.check_ngIf (/CommonModule/NgIf/wrapper.ngfactory.js:18:23)
    at CompiledTemplate.proxyViewClass.View_ModalDialogComponent0.detectChangesInternal (/AppModule/ModalDialogComponent/component.ngfactory.js:44:18)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4200/vendor.bundle.js:84228:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:84423:44)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:4200/vendor.bundle.js:84213:18)

**Comment by dabi-it** [comment]
I got it to work (in my webpack project) by:
adding a reference of jquery by adding the query reference to my project:
npm install jquery --save
then add to my app.component.ts

import * as $ from 'jquery';
window["$"] = $;
window["jQuery"] = $;

**Comment by Inlesco** [comment]
@dabi-it Your approach to this issue was probably the fastest and cleanest one whenever you need to setup something quickly, It worked for me.

Using: Webpack.
