### ISSUE TITLE
TypeError: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by tomaszcysewski** [dougludlow/ng2-bs3-modal#152]
Hello,

I implemented this modal and it works but console throws errors like this

`EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'close' of undefined
TypeError: Cannot read property 'close' of undefined
    at SafeSubscriber._next (http://localhost:4200/main.bundle.js:239:31)
    at SafeSubscriber.__tryOrUnsub (http://localhost:4200/vendor.bundle.js:566:16)
    at SafeSubscriber.next (http://localhost:4200/vendor.bundle.js:515:22)
    at Subscriber._next (http://localhost:4200/vendor.bundle.js:468:26)
    at Subscriber.next (http://localhost:4200/vendor.bundle.js:432:18)
    at FilterSubscriber._next (http://localhost:4200/vendor.bundle.js:55361:30)
    at FilterSubscriber.Subscriber.next (http://localhost:4200/vendor.bundle.js:432:18)
    at Subject.next (http://localhost:4200/vendor.bundle.js:1326:25)
    at http://localhost:4200/vendor.bundle.js:26589:40
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:136277:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:33813:37)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:136276:32)
    at Zone.run (http://localhost:4200/vendor.bundle.js:136148:43)
    at http://localhost:4200/vendor.bundle.js:136555:57
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:136310:35)`

what's the solution?

**Comment by dougludlow** [comment]
@tomaszcysewski what does your implementation look like? Take a look at #50, it's probably similar to what you are experiencing.
