### ISSUE TITLE
Error: Uncaught (in promise): ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by tuanmjnh** [dougludlow/ng2-bs3-modal#165]
Please help me!
I use angular 2 with asp.net core.
My Error:
**Exception: Call to Node module failed with error: Error: Uncaught (in promise): ReferenceError: jQuery is not defined
ReferenceError: jQuery is not defined
at ModalInstance.init (D:\Applications\Angular2CoreMVC2\ClientApp\dist\main-server.js:379:23)
at new ModalInstance (D:\Applications\Angular2CoreMVC2\ClientApp\dist\main-server.js:341:14)
at new ModalComponent (D:\Applications\Angular2CoreMVC2\ClientApp\dist\main-server.js:102:25)
at new Wrapper_ModalComponent (/Ng2Bs3ModalModule/ModalComponent/wrapper.ngfactory.js:6:18)
at AppView.View_ModalDemoComponent0.createInternal (/AppModule/ModalDemoComponent/component.ngfactory.js:183:31)
at AppView.create (D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:11951:25)
at AppView.View_ModalDemoComponent_Host0.createInternal (/AppModule/ModalDemoComponent/host.ngfactory.js:15:19)
at AppView.createHostView (D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:11964:25)
at ComponentFactory.create (D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:7361:29)
at ViewContainerRef_.createComponent (D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:9207:66)
at RouterOutlet.activate (D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:88499:44)
at ActivateRoutes.placeComponentIntoOutlet (D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:87779:20)
at ActivateRoutes.activateRoutes (D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:87746:30)
at D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:87682:62
at Array.forEach (native)
at new Error (native)
at resolvePromise (D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:74529:31) [angular]
at resolvePromise (D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:74500:17) [angular]
at D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:74577:17 [angular]
at Object.onInvokeTask (D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:4044:41) [angular]
at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:74230:36) [angular]
at Zone.module.exports.Zone.runTask (D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:74030:47) [<root> => angular]
at drainMicroTaskQueue (D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:74410:35) [<root>]
at ZoneTask.invoke (D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:74288:25) [<root>]
at data.args.(anonymous function) (D:\Applications\Angular2CoreMVC2\ClientApp\dist\vendor.js:75405:25) [<root>]
at _combinedTickCallback (internal/process/next_tick.js:80:11) [<root>]
at process._tickDomainCallback (internal/process/next_tick.js:128:9) [<root>]**

**Comment by dougludlow** [comment]
How are you including the modal in your project? What build tools are you using?

**Comment by kklingelsmith** [comment]
Just fyi,..  I had this same issue.  I'm using SPA templates, angular2, visual studio 2017, if that helps. 

// in modal-instance.ts
    private init() {
        this.$modal = jQuery(this.element.nativeElement); // << jQuery was undefined here

// Fix for me was changing
declare var jQuery: any;

// to this...
import * as jQuery from 'jquery';
