### ISSUE TITLE
this.$modal.modal is not a function

### ISSUE THREAD

**Issue by nicollaas94** [dougludlow/ng2-bs3-modal#182]
Hi 

On modal-instance.js Line 37, the function is trying to do a modal() in an array

`this.$modal.modal();`  
the $modal is an array

the exception:
```
TypeError: this.$modal.modal is not a function
    at ModalInstance.webpackJsonp.1036.ModalInstance.show (http://localhost:5550/0.chunk.js:659:21)
    at ModalInstance.webpackJsonp.1036.ModalInstance.open (http://localhost:5550/0.chunk.js:637:21)
    at ModalComponent.webpackJsonp.1021.ModalComponent.open (http://localhost:5550/0.chunk.js:197:30)
    at x.webpackJsonp.1031.x.open (http://localhost:5550/0.chunk.js:446:20)
    at CompiledTemplate.proxyViewClass.x0.handleEvent_27 (/XModule/XXComponent/component.ngfactory.js:1135:34)
    at CompiledTemplate.proxyViewClass.<anonymous> (http://localhost:5550/vendor.bundle.js:95531:37)
    at HTMLButtonElement.<anonymous> (http://localhost:5550/vendor.bundle.js:51452:53)
    at ZoneDelegate.webpackJsonp.361.ZoneDelegate.invokeTask (http://localhost:5550/polyfills.bundle.js:2374:31)
    at Object.onInvokeTask (http://localhost:5550/vendor.bundle.js:32280:37)
    at ZoneDelegate.webpackJsonp.361.ZoneDelegate.invokeTask (http://localhost:5550/polyfills.bundle.js:2373:36)
    at Zone.webpackJsonp.361.Zone.runTask (http://localhost:5550/polyfills.bundle.js:2173:47)
    at HTMLButtonElement.ZoneTask.invoke (http://localhost:5550/polyfills.bundle.js:2427:38)
ERROR CONTEXT:
DebugContext {_view: CompiledTemplate.proxyViewClass, _nodeIndex: 27, _tplRow: 17, _tplCol: 0}
ViewWrappedError
```

**Comment by wartab** [comment]
$modal cannot be an array, it is always supposed to be an instance of jQuery. Can you show your code?

**Comment by nicollaas94** [comment]
I followed the angular-cli sample, more specific, I was trying to implement this [page](https://github.com/dougludlow/ng2-bs3-modal-demo-angular-cli/blob/master/src/app/app.component.html)

**Comment by dougludlow** [comment]
@nicollaas94 could you post more code samples. It's hard to troubleshoot without more information.

**Comment by DmitryEfimenko** [comment]
+1
I get the same issue

**Comment by dougludlow** [comment]
@DmitryEfimenko this usually has to do with jquery or bootstrap not being included properly.

**Comment by dougludlow** [comment]
Closing for now. Feel free to reopen if you are still having issues.
