### ISSUE TITLE
Demo page is blank due to forbidden error

### ISSUE THREAD

**Issue by raghav710** [dougludlow/ng2-bs3-modal#200]
Navigating to http://dougludlow.github.io/ng2-bs3-modal/
gives a blank page. The console error says

> Failed to load resource: the server responded with a status of 403 (Forbidden)
dougludlow.github.io/:22 Error: (SystemJS) XHR error (403 Forbidden) loading http://dougludlow.github.io/ng2-bs3-modal/demo/main.ts

>	Error: XHR error (403 Forbidden) loading http://dougludlow.github.io/ng2-bs3-modal/demo/main.ts
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (https://unpkg.com/zone.js@0.6.21/dist/zone.js:628:29)
	    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.6.21/dist/zone.js:225:37)
	    at Zone.runTask (https://unpkg.com/zone.js@0.6.21/dist/zone.js:125:47)
	    at XMLHttpRequest.ZoneTask.invoke (https://unpkg.com/zone.js@0.6.21/dist/zone.js:293:33)
	Error loading http://dougludlow.github.io/ng2-bs3-modal/demo/main.ts
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (https://unpkg.com/zone.js@0.6.21/dist/zone.js:628:29)
	    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.6.21/dist/zone.js:225:37)
	    at Zone.runTask (https://unpkg.com/zone.js@0.6.21/dist/zone.js:125:47)
	    at XMLHttpRequest.ZoneTask.invoke (https://unpkg.com/zone.js@0.6.21/dist/zone.js:293:33)
	Error loading http://dougludlow.github.io/ng2-bs3-modal/demo/main.ts
(anonymous) @ dougludlow.github.io/:22

**Comment by dougludlow** [comment]
@raghav710 thanks for reporting this. It should be working again!
