### ISSUE TITLE
error on build in windows 10

### ISSUE THREAD

**Issue by born2net** [dougludlow/ng2-bs3-modal#45]
```
c:\msweb\ng2-bs3-modal>npm run build

> ng2-bs3-modal-born2net@0.2.5 build c:\msweb\ng2-bs3-modal
> npm run clean && npm run lint && npm run tsc && npm run bundles


> ng2-bs3-modal-born2net@0.2.5 clean c:\msweb\ng2-bs3-modal
> node ./node_modules/.bin/rimraf ./bundles/ ./components/ ./ng2-bs3-modal.js ./ng2-bs3-modal.d.ts

c:\msweb\ng2-bs3-modal\node_modules\.bin\rimraf:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by born2net** [comment]
had to install globally rmraf in win 10

**Comment by fuitattila** [comment]
By me still exists this problem. I have also Windows 10. And had installed rmrf and rimraf globally, but still fails the install with same error. Maybe you have an other package installed globally?
@born2net Please help with an other tip!

Tahk you!

**Comment by born2net** [comment]
fixes for windows: https://github.com/born2net/ng2-bs3-modal/blob/master/package.json
