### ISSUE TITLE
Modals in ngFor

### ISSUE THREAD

**Issue by guzmo** [dougludlow/ng2-bs3-modal#55]
Hey!

Im getting problems when I'm running this in an *ngFor.

```
"EXCEPTION: Error in /app/components/application/resource-panel/resource-panel.html:52:62
↵ORIGINAL EXCEPTION: TypeError: self._ModalComponent_62_4 is not a function
↵ORIGINAL STACKTRACE:↵TypeError: self._ModalComponent_62_4 is not a function
↵    at DebugAppView._View_ResourcePanelComponent0._handle_submit_72_0 (ResourcePanelComponent.template.js:812:20)
↵    at eval (eval at <anonymous> (http://localhost:8081/bundle.js:1:0), <anonymous>:316:24)
↵    at eval (eval at <anonymous> (http://localhost:8081/bundle.js:1:0), <anonymous>:278:36)
↵    at eval (eval at <anonymous> (http://localhost:8081/bundle.js:1:0), <anonymous>:20:93)
↵    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8081/bundle.js:1:0), <anonymous>:323:29)
↵    at Object.NgZoneImpl.inner.inner.fork.onInvoke (eval at <anonymous> (http://localhost:8081/bundle.js:1:0), <anonymous>:45:41)
↵    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8081/bundle.js:1:0), <anonymous>:322:35)
↵    at Zone.runGuarded (eval at <anonymous> (http://localhost:8081/bundle.js:1:0), <anonymous>:230:48)
↵    at NgZoneImpl.runInnerGuarded (eval at <anonymous> (http://localhost:8081/bundle.js:1:0), <anonymous>:78:78)
↵    at NgZone.runGuarded (eval at <anonymous> (http://localhost:8081/bundle.js:1:0), <anonymous>:228:73)
↵ERROR CONTEXT:↵[object Object]"
```

Any suggestions?

**Comment by dougludlow** [comment]
Hey @guzmo, can you show me some of your code? That would help me figure out what's going on.

**Comment by guzmo** [comment]
I have a component like this.

```
<resource-panel *ngFor="let resource of application.resources" class="col-lg-4 col-sm-6 col-xs-12 resource" [resource]="resource"></resource-panel>
```
In that component I have a modal. I can open it but when I press "Ok" it throws this exception.

I have a form in the Modal that gets created by following.

```
this.createAttributeForm = this.fb.group({
   name: ['', Validators.required],
   type: ['', Validators.required]
});
```

The Modal is similar to this and is in my template for the **resource-panel** Component.
```
<modal #createAttribute>
    <modal-header>
        <h4 class="modal-title">Create attribute</h4>
    </modal-header>
    <modal-body>
        <form role="form" [ngFormModel]="createAttributeForm" (submit)="createAttribute()">
            <div class="form-group">
                <label for="name">Name</label>
                <input autofocus ngControl="name" required type="text" class="form-control" id="name">
            </div>     
            <div class="form-group">
                <label for="type">Type</label>
                <select ngControl="type" required type="text" class="form-control" id="type">
                    <option></option>
                    <option *ngFor="let type of types" [value]="type">{{type}}</option>
                </select>    
            </div> 
            <button type="button" class="btn btn-default" data-dismiss="modal" (click)="modal.dismiss()">Cancel</button>
            <button type="submit" [disabled]="!createAttributeForm.valid" class="btn btn-primary">Ok</button>    
        </form>
    </modal-body>
</modal>
```

Getting the Modal with 
```
@ViewChild('createAttribute')
 modal: ModalComponent;
```
as usual.

I'm too new to Angular2/Typescript to know the best way to handle this Modal. It feels bad to create one for every iteration as I am doing now.

**Comment by dougludlow** [comment]
Hmm... I wonder if it's because bootstrap.js is not being loaded? How are you building your app? webpack?

**Comment by dougludlow** [comment]
Does the modal load outside of the ngFor?

**Comment by guzmo** [comment]
ye and it loads inside as well, the only thing I cant do is press "Ok" on the submit button because then it crashes and reloads the page.

**Comment by dougludlow** [comment]
What does your `createAttribute()` function look like?

**Comment by guzmo** [comment]
At the moment nothing. Just a console.log while testing it.

**Comment by dougludlow** [comment]
Hmm... I'm not sure if I've used a form submit yet, in the modal. I'll have to do some testing around that. I wonder if you still get the issue if you swap the submit for a plain ol' button?

**Comment by guzmo** [comment]
Ill try it. Im not home for 2 days though so can have something for u on friday the earliest, just so u know :)

**Comment by guzmo** [comment]
Sorry for the delay but its the same error with an ol' button :P
Can I somehow create the modal outside of the dialog and call it from inside the loop?

**Comment by guzmo** [comment]
Have you had any time to debug this? :)

**Comment by dougludlow** [comment]
I believe this has been resolved in Angular itself. I have tested having the modal in NgFor and it appears to work as expected.
